services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload
    env_file: 
          - .env
    volumes:
      - ./backend:/app  
      - ${MATERIALS_FOLDER}:/materials
      - ${ENVISIONHGDETECTOR_OUTPUT}:/envisionhgdetector_output

  frontend:
    build:
      context: ./frontend
      dockerfile:  Dockerfile # dockerfile_build # Dockerfile # dockerfile_build for production build
      args:
        - NEXT_PUBLIC_PREVIEW=${NEXT_PUBLIC_PREVIEW}
        - NEXT_PUBLIC_ANALYSIS=${NEXT_PUBLIC_ANALYSIS}
        - NEXT_PUBLIC_ANALYTICS=${NEXT_PUBLIC_ANALYTICS}
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    env_file: 
          - .env
    environment:
    - NEXT_PUBLIC_PREVIEW=${NEXT_PUBLIC_PREVIEW}
    - NEXT_PUBLIC_ANALYSIS=${NEXT_PUBLIC_ANALYSIS}
    - NEXT_PUBLIC_ANALYTICS=${NEXT_PUBLIC_ANALYTICS}
    - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    volumes: # comment it for production build
      - ./frontend:/app  
      - /app/node_modules