services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: 
          - .env
    volumes:
      - ./backend:/app  
      - ${MATERIALS_FOLDER}:/materials
      - ${ENVISIONHGDETECTOR_OUTPUT}:/envisionhgdetector_output

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    depends_on:
      - backend
    env_file: 
          - .env
    volumes:
      - ./frontend:/app  
      - /app/node_modules