FROM python:3.9

RUN apt-get update && apt-get install -y libgl1 ffmpeg && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip 

WORKDIR /app 

RUN pip install torch torchvision
RUN pip install envisionhgdetector
RUN pip install bertopic transformers librosa nltk openai-whisper

CMD ["python", "-u", "prepare_materials.py"]