"""Pause and filler word detection from transcripts and audio.

Detects:
- Silent pauses (gaps between SRT subtitle segments > threshold)
- Filled pauses / fillers ("um", "uh", "like", "you know", "so", "er", "ah")
- Speech rate (words per minute per segment)

Uses existing Whisper SRT transcripts (already generated by prepare_materials.py).

Outputs per video: {video_name}_pauses_fillers.json
"""

import glob
import json
import logging
import os
import re

import librosa
import numpy as np

logger = logging.getLogger(__name__)

# Common English filled pauses and discourse markers
FILLER_WORDS = {
    "um", "uh", "uhm", "umm", "er", "ah", "hmm",
    "like", "so", "actually", "basically", "literally",
    "you know", "i mean", "kind of", "sort of",
}

# Single-word fillers for fast lookup
FILLER_SINGLES = {w for w in FILLER_WORDS if " " not in w}
# Multi-word fillers
FILLER_PHRASES = {w for w in FILLER_WORDS if " " in w}

# Minimum gap between SRT segments to count as a "pause" (seconds)
PAUSE_THRESHOLD = 0.5


def parse_srt(srt_path: str) -> list[dict]:
    """Parse an SRT file into a list of segments with timestamps and text."""
    segments = []
    with open(srt_path, "r", encoding="utf-8") as f:
        content = f.read()

    # SRT blocks separated by blank lines
    blocks = re.split(r"\n\s*\n", content.strip())

    for block in blocks:
        lines = block.strip().split("\n")
        if len(lines) < 3:
            continue

        # Parse timestamp line: 00:00:01,000 --> 00:00:04,500
        ts_match = re.match(
            r"(\d{2}:\d{2}:\d{2}[,\.]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,\.]\d{3})",
            lines[1],
        )
        if not ts_match:
            continue

        start = _srt_time_to_seconds(ts_match.group(1))
        end = _srt_time_to_seconds(ts_match.group(2))
        text = " ".join(lines[2:]).strip()

        segments.append({"start": start, "end": end, "text": text})

    return segments


def _srt_time_to_seconds(ts: str) -> float:
    """Convert SRT timestamp (HH:MM:SS,mmm) to seconds."""
    ts = ts.replace(",", ".")
    parts = ts.split(":")
    return float(parts[0]) * 3600 + float(parts[1]) * 60 + float(parts[2])


def detect_pauses(segments: list[dict]) -> list[dict]:
    """Detect silent pauses between transcript segments."""
    pauses = []
    for i in range(1, len(segments)):
        gap = segments[i]["start"] - segments[i - 1]["end"]
        if gap >= PAUSE_THRESHOLD:
            pauses.append({
                "start": segments[i - 1]["end"],
                "end": segments[i]["start"],
                "duration": round(gap, 3),
                "after_text": segments[i - 1]["text"],
            })
    return pauses


def detect_fillers(segments: list[dict]) -> list[dict]:
    """Detect filler words and phrases in transcript segments."""
    fillers = []
    for seg in segments:
        text_lower = seg["text"].lower()
        words = text_lower.split()

        # Single-word fillers
        for word in words:
            clean = re.sub(r"[^\w']", "", word)
            if clean in FILLER_SINGLES:
                fillers.append({
                    "word": clean,
                    "start": seg["start"],
                    "end": seg["end"],
                    "context": seg["text"],
                })

        # Multi-word fillers
        for phrase in FILLER_PHRASES:
            if phrase in text_lower:
                fillers.append({
                    "word": phrase,
                    "start": seg["start"],
                    "end": seg["end"],
                    "context": seg["text"],
                })

    return fillers


def compute_speech_rate(segments: list[dict]) -> list[dict]:
    """Compute words per minute for each segment."""
    rates = []
    for seg in segments:
        duration = seg["end"] - seg["start"]
        if duration <= 0:
            continue
        word_count = len(seg["text"].split())
        wpm = (word_count / duration) * 60
        rates.append({
            "start": seg["start"],
            "end": seg["end"],
            "wpm": round(wpm, 1),
            "word_count": word_count,
        })
    return rates


def detect_audio_silences(
    audio_path: str,
    top_db: int = 30,
    min_silence_duration: float = 0.5,
) -> list[dict]:
    """Detect silences directly from audio using librosa.

    Complements the SRT-based pause detection with acoustic evidence.
    """
    y, sr = librosa.load(audio_path, sr=None)
    # Split on silence — returns intervals of non-silent audio
    intervals = librosa.effects.split(y, top_db=top_db)

    silences = []
    for i in range(1, len(intervals)):
        silence_start = intervals[i - 1][1] / sr
        silence_end = intervals[i][0] / sr
        duration = silence_end - silence_start
        if duration >= min_silence_duration:
            silences.append({
                "start": round(silence_start, 3),
                "end": round(silence_end, 3),
                "duration": round(duration, 3),
            })

    return silences


def extract_pauses_fillers(video_folder: str) -> None:
    """Extract pauses and fillers for a single video."""
    base_name = os.path.basename(video_folder)
    output_path = os.path.join(video_folder, f"{base_name}_pauses_fillers.json")
    if os.path.exists(output_path):
        return

    # Find the SRT transcript
    srt_path = os.path.join(video_folder, f"{base_name}_transcript.srt")
    if not os.path.exists(srt_path):
        logger.warning(f"No SRT transcript found for {base_name}, skipping")
        return

    logger.info(f"Extracting pauses and fillers for {base_name}")

    segments = parse_srt(srt_path)
    if not segments:
        logger.warning(f"Empty transcript for {base_name}")
        return

    pauses = detect_pauses(segments)
    fillers = detect_fillers(segments)
    speech_rates = compute_speech_rate(segments)

    # Audio-based silence detection
    audio_path = os.path.join(video_folder, f"{base_name}_audio.wav")
    audio_silences = []
    if os.path.exists(audio_path):
        audio_silences = detect_audio_silences(audio_path)

    # Summary statistics
    total_duration = segments[-1]["end"] - segments[0]["start"] if segments else 0
    total_words = sum(len(seg["text"].split()) for seg in segments)

    result = {
        "pauses": pauses,
        "fillers": fillers,
        "speech_rates": speech_rates,
        "audio_silences": audio_silences,
        "summary": {
            "total_pauses": len(pauses),
            "total_fillers": len(fillers),
            "avg_pause_duration": round(
                np.mean([p["duration"] for p in pauses]), 3
            ) if pauses else 0,
            "max_pause_duration": round(
                max(p["duration"] for p in pauses), 3
            ) if pauses else 0,
            "filler_rate_per_minute": round(
                (len(fillers) / total_duration) * 60, 2
            ) if total_duration > 0 else 0,
            "avg_speech_rate_wpm": round(
                np.mean([r["wpm"] for r in speech_rates]), 1
            ) if speech_rates else 0,
            "total_words": total_words,
            "total_duration_s": round(total_duration, 1),
            "filler_word_counts": _count_fillers(fillers),
        },
    }

    with open(output_path, "w") as f:
        json.dump(result, f)

    logger.info(f"Saved pauses/fillers to {output_path}")


def _count_fillers(fillers: list[dict]) -> dict[str, int]:
    """Count occurrences of each filler word."""
    counts: dict[str, int] = {}
    for f in fillers:
        word = f["word"]
        counts[word] = counts.get(word, 0) + 1
    return dict(sorted(counts.items(), key=lambda x: x[1], reverse=True))


def setup_pause_filler_analysis(materials_folder: str = "/materials") -> None:
    """Run pause/filler analysis for all videos."""
    video_folders = glob.glob(os.path.join(materials_folder, "*"))
    video_folders = [f for f in video_folders if os.path.isdir(f)]

    for folder in video_folders:
        extract_pauses_fillers(folder)
